language: go
go_import_path: github.com/matthewhartstonge/hasher
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure -v
  # if we have go mod support, use it
  - go mod vendor || true

script:
  - go test ./...
